CREATE TABLE `product` (
    `id`                BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name`              VARCHAR(200)  NOT NULL COMMENT '商品名称',
    `sku`               VARCHAR(100)  NOT NULL COMMENT '商品编号(SKU)',
    `category`          VARCHAR(100)  NOT NULL COMMENT '商品分类',
    `brand`             VARCHAR(100)           DEFAULT NULL COMMENT '品牌',
    `points_price`      INT           NOT NULL COMMENT '积分价格',
    `market_price`      DECIMAL(10,2)          DEFAULT NULL COMMENT '市场参考价',
    `stock`             INT           NOT NULL DEFAULT 0 COMMENT '当前库存',
    `sold_count`        INT           NOT NULL DEFAULT 0 COMMENT '已兑换数量',
    `status`            TINYINT       NOT NULL DEFAULT 0 COMMENT '状态 0-已下架 1-已上架',
    `description`       TEXT                   DEFAULT NULL COMMENT '商品描述',
    `image_url`         VARCHAR(500)           DEFAULT NULL COMMENT '主图URL',
    `subtitle`          VARCHAR(500)           DEFAULT NULL COMMENT '副标题/卖点',
    `delivery_method`   VARCHAR(200)           DEFAULT NULL COMMENT '配送方式',
    `service_guarantee` VARCHAR(500)           DEFAULT NULL COMMENT '服务保障',
    `promotion`         VARCHAR(200)           DEFAULT NULL COMMENT '促销活动',
    `colors`            VARCHAR(500)           DEFAULT NULL COMMENT '可选颜色(逗号分隔)',
    `specs`             JSON                   DEFAULT NULL COMMENT '规格参数(JSON)',
    `created_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by`        BIGINT                 DEFAULT NULL COMMENT '创建人',
    `updated_by`        BIGINT                 DEFAULT NULL COMMENT '更新人',
    `deleted`           TINYINT       NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    `version`           INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_sku` (`sku`),
    INDEX `idx_name` (`name`),
    INDEX `idx_category` (`category`),
    INDEX `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品表';
